name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -ldflags="-s -w" -o charge-current ./go/run.go

    - name: Test
      run: go build -ldflags="-s -w" -o charge-current ./go/run.go
